name: Publish .NET package to NuGet

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/ConsoleMenuDN/ConsoleMenuDN.csproj

    - name: Build project
      run: dotnet build --configuration Release --no-restore ./src/ConsoleMenuDN/ConsoleMenuDN.csproj

    - name: Pack project
      run: dotnet pack --configuration Release --no-build --output ./nupkg ./src/ConsoleMenuDN/ConsoleMenuDN.csproj

    - name: Publish package to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
